### PR TITLE
Added Dice_Game

### PR DESCRIPTION
**Pull request by shivani-tripurari**
Added Dice_Game folder which contains html,css,js and pictures into the games folder.Also, added into data and routes

### CODE REVIEW

**Comment by shivani-tripurari** [comment]
Can you please help me!

**Comment by Swapnil-2503** [comment]
@shivani-tripurari <Route path="/Dice_Game" element={<Dice_Game />} />//close this

**Comment by shivani-tripurari** [comment]
> @shivani-tripurari <Route path="/Dice_Game" element={<Dice_Game />} />//close this 

Thank you!!

**Review by shivani-tripurari — COMMENTED** [review]
Updated AllRoutes.js

**Review by shivani-tripurari — COMMENTED** [review]
Added dice game

**Review by raj03kumar — COMMENTED** [review]
This is ReactJS repository and u r requested to contribute in react ONLY and not just HTML. CSS AND JS

**Pull request closed without merging**
