### PR TITLE
Re-Play Button added

### PR DESCRIPTION
**Pull request by ishita80**
Re-Play button is added to Ninty-Nine game.

### CODE REVIEW

**Comment by raj03kumar** [comment]
> Re-Play button is added to Ninty-Nine game.

There has been some issue Ishita. We will resolve the conflicts and your work will be merged. Thanks for contributing....

**Comment by ishita80** [comment]
Okay Sir. Thank you

**Comment by raj03kumar** [comment]
> Okay Sir. Thank you

Ishita the problem is that u haven't pull the repository and your branch is behind our main branch. First sync your fork and then send a pull request. It happens sometimes...dont worry

**Review by raj03kumar — APPROVED** [review]
Good work...

**Pull request merged**
