### PR TITLE
Added the AI mode in tictactoe

### LINKED ISSUE #324: [Feature Request]: Want to add AI mode in Tic-Tac-toe
### How would you like to enhance the existing project.

I want to add AI mode in Tic-Tac-Toe game which will help the users to play alone without any other player.

### Describe breifly how would you implement the same.

I will implement it using javascript logic and algorithm. Also I have readymade code available for that.
image
image

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

### PR DESCRIPTION
**Pull request by AyishikD**
I have added the AI mode in tic tac toe
closes #324 
Please kindly check it

### CODE REVIEW

**Review by raj03kumar — APPROVED** [review]
Brilliant work...

**Comment by raj03kumar** [comment]
@AyishikD Hey you have done brilliant work but there is some merge conflict in ur PR so i am unable to merge it. Kindly resolve it so that i can merge further.

**Review by raj03kumar — CHANGES_REQUESTED** [review]
Resolve the merge conflicts

**Comment by AyishikD** [comment]
Hey @raj03kumar can u assist me in helping to resolve merge conflicts

**Comment by raj03kumar** [comment]
> Hey @raj03kumar can u assist me in helping to resolve merge conflicts

Go to your fork repository.
- Sync the branch

**Comment by raj03kumar** [comment]
> > Hey @raj03kumar can u assist me in helping to resolve merge conflicts
> 
> Go to your fork repository.
> 
> * Sync the branch

Merge conflicts happens when u r working on older fork

**Pull request closed without merging**
