### PR TITLE
Added about section in homepage

### PR DESCRIPTION
**Pull request by linga66**
As mentioned in issue id #498  , I have updated the homepage by adding the about section.

Screenshot (600)

### CODE REVIEW

**Comment by linga66** [comment]
@cleveranu Do check this

**Comment by raj03kumar** [comment]
@linga66 Can you please make changes to the design as it is contradicting with the main animation.

**Comment by linga66** [comment]
What colour do you want me to put?

**Comment by linga66** [comment]
Screenshot (615)

Is this Okay? @raj03kumar

**Comment by raj03kumar** [comment]
> Screenshot (615)
> 
> Is this Okay? @raj03kumar

yeah it's okay. But don't compromise with the main height of the pacman animation.

**Comment by linga66** [comment]
> > Screenshot (615)
> > Is this Okay? @raj03kumar
> 
> yeah it's okay. But don't compromise with the main height of the pacman animation.

Screenshot (616)
I=
The pacman animation is good

**Comment by raj03kumar** [comment]
> > > Screenshot (615)
> > > Is this Okay? @raj03kumar
> > 
> > 
> > yeah it's okay. But don't compromise with the main height of the pacman animation.
> 
> Screenshot (616) I= The pacman animation is good

Yeah the animation is good but don't decrease the height of the pacman animation. It should be little big. You made it to half. Kindly improve on that.

**Comment by raj03kumar** [comment]
image
make changes in this part.

**Comment by linga66** [comment]
> > > > Screenshot (615)
> > > > Is this Okay? @raj03kumar
> > > 
> > > 
> > > yeah it's okay. But don't compromise with the main height of the pacman animation.
> > 
> > 
> > Screenshot (616) I= The pacman animation is good
> 
> Yeah the animation is good but don't decrease the height of the pacman animation. It should be little big. You made it to half. Kindly improve on that.

It was mentioned in issue id #497 , and was merged into the main branch.

**Comment by linga66** [comment]
Changes are done
@raj03kumar

**Comment by raj03kumar** [comment]
> Changes are done @raj03kumar

Good.

**Pull request merged**
