### PR TITLE
homepage responsiveness fixed

### PR DESCRIPTION
**Pull request by Sammydepoj**
Homepage responsiveness fixed which resolves issue #8

### CODE REVIEW

**Review by nandurijv — CHANGES_REQUESTED** [review]
Cards need to be centre aligned. They are more left aligned.
width should be 100%, use padding instead.
Screenshot 2022-10-04 at 3 53 47 PM
Similarly change the width percentage.
Screenshot 2022-10-04 at 3 52 41 PM

**Comment by Sammydepoj** [comment]
Alright. I'm on it

**Review by nandurijv — CHANGES_REQUESTED** [review]
The card box seems to still looks left aligned. Please look into this.
Screenshot 2022-10-05 at 8 03 11 PM

**Comment by Sammydepoj** [comment]
Alright. I would

**Review by nandurijv — APPROVED** [review]
Looks Clean! Good Job!

**Pull request merged**
