### PR TITLE
catch_the_bottle_added

### PR DESCRIPTION
**Pull request by Adithya212**
Added the game

### CODE REVIEW

**Comment by raj03kumar** [comment]
@panwar8279 Hey how can you merge any PR without going through the code. Is this even React.js
If you don't understand the code then you should assign any reviewers and after their approval you should merge. This is against CODE OF CONDUCT.

**Comment by Adithya212** [comment]
I'm really sorry for the mistake,it was my first pr.

**Comment by Adithya212** [comment]
I'm working on the project in Reactjs

**Comment by raj03kumar** [comment]
Yes, u can

**Pull request merged**
