### PR TITLE
Improve Animation for mobile devices

### LINKED ISSUE #360: [Feature Request]: Make the animation responsive
### How would you like to enhance the existing project.

Enhancement: Make the animation responsive for the mobile devices.

### Describe breifly how would you implement the same.

Solution_steps: You have to write media queries to make the animation responsive.

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

### PR DESCRIPTION
**Pull request by Ayush9951**
close #360 
Hi @raj03kumar, I've successfully added media queries, It will Improve responsiveness for mobile devices. please consider merging the pull request.

Screenshot 2023-06-05 191127

### CODE REVIEW

**Review by raj03kumar — CHANGES_REQUESTED** [review]
Ayush you did everything correctly. can you improve it a little more for other dimensions like tabs and make the website more responsive.

**Comment by Ayush9951** [comment]
Hi @raj03kumar, I've only added media queries for devices with width <= 576px, other common device widths are - 768px, 992px, 1200px, 1400px. Shall I make It responsive for all these widths. But only If any specific widths please mention.

**Comment by Ayush9951** [comment]
ok, I'll add the media queries for other device widths also, but It will take some time.

**Review by raj03kumar — APPROVED** [review]
Good Work Ayush...

**Pull request merged**
