### PR TITLE
Brick breakout  #86

### PR DESCRIPTION
**Pull request by meihu-ganesh**
Here is the game: Brick Breakout, please review @raj03kumar @Shreyaar12 
also this closes the issue #86

### CODE REVIEW

**Comment by meihu-ganesh** [comment]
Can I know what's is the reason for the failure of these checks?
I don't understand

**Review by raj03kumar — COMMENTED** [review]
Kindly go through the contributing.md

**Comment by meihu-ganesh** [comment]
yes, I had figured out, and commited it in the latest commit (https://github.com/ssitvit/Games-and-Go/pull/133/commits/9239a9547732861b87ad24ebe28bdd6503dfde79)

**Comment by raj03kumar** [comment]
> yes, I had figured out, and commited it in the latest commit ([9239a95](https://github.com/ssitvit/Games-and-Go/commit/9239a9547732861b87ad24ebe28bdd6503dfde79))

Create a new pull request

**Pull request closed without merging**
