### PR TITLE
Fixed issue #452

### PR DESCRIPTION
**Pull request by Pranav-Rustagi**

### CODE REVIEW

**Comment by raj03kumar** [comment]
@panwar8279 This was an invalid PR. Please review it properly before merging the PR's. 
And you assigned this person labels as well. Please review properly @panwar8279 .

**Comment by raj03kumar** [comment]
@panwar8279 I shall walk you through the steps before merging any PR.

- First check the deployment website. You can see that from here.
image
- If you really think the changes are made accordingly then only merge.
- **Also go through the files changed to catch the invalid PR's**
image
- If you think that it is invalid then don't merge it.
- If you see that it is made using just HTML, CSS and JS without React Framework then also don't merge it.

Hope you understand us and work accordingly. We are so happy working with you @panwar8279 . Appreciate your hard work.

**Comment by Pranav-Rustagi** [comment]
@raj03kumar May I ask how it is an invalid PR? Are the PRs supposed to be strictly React JS based, since this issue was regarding the deployment?

**Comment by raj03kumar** [comment]
> @raj03kumar May I please ask how it is an invalid PR? Are the PRs supposed to be strictly React JS based, since this issue was regarding the deployment?

image
What kind of pull request is this.

Yes the PR's are to be in react only. Else it won't work on the website.

**Comment by Pranav-Rustagi** [comment]
@raj03kumar Being very polite, could you please checkout issue #452? Please try to reproduce it, I have mentioned the steps to reproduce it in the issue. Since you have reverted the merge, the issue is back. You can also try to check out the deployment preview from my pull request. You will find that issue does not appear there.

**Comment by raj03kumar** [comment]
@Pranav-Rustagi Alright, we apologize for the inconvenience which was caused due to lack of communication.
image
Always share something about your PR, else it looks like invalid.

If you are willing then you can recontribute into this issue Pranav.

**Comment by Pranav-Rustagi** [comment]
@raj03kumar Sure

**Comment by Pranav-Rustagi** [comment]
@raj03kumar @panwar8279 Could you please add lables to the PR.

**Pull request merged**
