### PR TITLE
added a new game

### PR DESCRIPTION
**Pull request by Aryan123-rgb**
Kindly review it and tell me if any necessary changes are required :)

### CODE REVIEW

**Comment by raj03kumar** [comment]
The game is good but there is some problem with the direction. It doesn't fire in the direction of click rather it is inclined with some angle. Fix this issue.

**Comment by raj03kumar** [comment]
> > The game is good but there is some problem with the direction. It doesn't fire in the direction of click rather it is inclined with some angle. Fix this issue.
> 
> Yeah I tried fixing it and tried to fix it as much as I can. The only error is that you need to adjust the screen before playing it I really tried adjusting the screen but the game wasn't working . If you still find the pr close worthy, let me know because really sorry I can't adjust the game to fit in the screen
> 
>  Untitled.3.mp4
There is something wrong in your CSS.
Try changing the position of the screen or reduce the width.

**Comment by Aryan123-rgb** [comment]
> > > The game is good but there is some problem with the direction. It doesn't fire in the direction of click rather it is inclined with some angle. Fix this issue.
> > 
> > 
> > Yeah I tried fixing it and tried to fix it as much as I can. The only error is that you need to adjust the screen before playing it I really tried adjusting the screen but the game wasn't working . If you still find the pr close worthy, let me know because really sorry I can't adjust the game to fit in the screen
> > Untitled.3.mp4
> 
> There is something wrong in your CSS. Try changing the position of the screen or reduce the width.

Still you would have to scroll down ,the game uses the logic of clientX and clientY to detect the mouse position and fire the projectiles accordingly . If I try to shrink it ,the directions won't work and the game will break

**Review by raj03kumar — APPROVED** [review]
Could have been better.

**Comment by Aryan123-rgb** [comment]
> Could have been better.

Sorry :). Will try my best to meet your expectations the next time.

**Pull request merged**
