### PR TITLE
[GSSoC'23] Guess Number Game Ready

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
Issue Number - 693
Title - Guess The Number

Closes issue #693 

<br>

image

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@admindebu @panwar8279 please review this pull request

**Comment by Avdhesh-Varshney** [comment]
@admindebu @panwar8279 sir, i have created this pr 4 days ago. But no action has done on this pr. Please review this pull request

**Comment by Avdhesh-Varshney** [comment]
@Shreyaar12 @admindebu @panwar8279 I have created this pr 10 days ago. Still there will be no review on this pr.
I requested to review this pr as soon as possible.

**Comment by Avdhesh-Varshney** [comment]
@Shreyaar12 @admindebu @panwar8279 I have created this pr more than 2 weeks ago. Still there will be no review on this pr.
I requested to review this pr as soon as possible.

**Comment by panwar8279** [comment]
Please Create new PRs for this because it contains conflict issue.

**Pull request closed without merging**
