### PR TITLE
Fixed #339 - Implemented Music Toggle Button

### LINKED ISSUE #339: [Feature Request]: Single Button for Music On/Off
### How would you like to enhance the existing project.

Enhancement : Instead of two buttons for music control there can be a single button for music control that too on the bottom left of the site so one can toggle it from any scroll position

### Describe breifly how would you implement the same.

I Will Remove the buttons for music on/off and instead following the same design language create a new button for the same

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

### PR DESCRIPTION
**Pull request by ManasMadan**
Added the Feature of Music Toggle Button following the same design language

Closes issue #339 

image

### CODE REVIEW

**Review by raj03kumar — APPROVED** [review]
Good work...

**Comment by ManasMadan** [comment]
Thanks @raj03kumar, are there any issues/features you want me to work on

**Comment by raj03kumar** [comment]
> Thanks @raj03kumar, are there any issues/features you want me to work on

You can look from the issue section.
Would you like to loop the pacman animation so that it is always running.

**Comment by ManasMadan** [comment]
Yes @raj03kumar, would like to work on it

**Pull request merged**
