### PR TITLE
Created Tenzies Game

### PR DESCRIPTION
**Pull request by Nishitbaria**
Dies Game When All Numbers Become same You Won The Game

image

### CODE REVIEW

**Comment by Nishitbaria** [comment]
@raj03kumar Please Review my pull request for Tenzies Games

**Comment by raj03kumar** [comment]
Resolve the conflicts

**Comment by raj03kumar** [comment]
@Nishitbaria there is some issue with your pull request. The website got right padding because of some CSS from ur PR. Kindly Fix  this issue else we will revert your PR.

**Comment by Nishitbaria** [comment]
I will do it in short time

**Comment by Nishitbaria** [comment]
Hey, @raj03kumar, I need your help to address the problem. What would you suggest I do? Should I create a new issue specifically for this matter?

**Pull request merged**
