### PR TITLE
Added new game: Arkanoid 

### LINKED ISSUE #427: New game Arkanoid
### Description

I want to add Arkanoid game .
assign me this under GSSOC'2023
reference google image of game given below its not build yet 

### Screenshots

Screenshot 2023-06-08 125202

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Swapnil-2503**
close #427 
>added game arkanoid with adding in allroutes, data its working fine
completed task #427 

https://github.com/ssitvit/Games-and-Go/assets/89910173/07b1afd0-eb84-47fa-b55f-2270db69c1bb

### CODE REVIEW

**Comment by Swapnil-2503** [comment]
Can you add Gssoc'23 label here you got missed

**Comment by Swapnil-2503** [comment]
@panwar8279

**Comment by Swapnil-2503** [comment]
please add Gssoc label as it will count in contributions for certificate @panwar8279

**Comment by raj03kumar** [comment]
@panwar8279 Please follow the guidelines. You haven't provided the labels to @Swapnil-2503. His contribution will not count. 

THIS IS LAST WARNING TO YOU @panwar8279. Your mentorship will be dismissed you you break the guidelines.

**Comment by raj03kumar** [comment]
@Swapnil-2503 can you recontribute. I will provide you labels for that PR

**Pull request merged**
