### PR TITLE
[GSSoC'23] Fifteen Game Project Completed

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
Title - Fifteen Game
Issue Number - 695

close issue #695 

<br>

image

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@admindebu @panwar8279 sir, please review this pr

**Comment by Shreyaar12** [comment]
Please refer the documentation. Checks have failed

**Comment by Avdhesh-Varshney** [comment]
@Shreyaar12 @admindebu @panwar8279 please review this pull request. I have raised this pr 3 weeks ago. I requested to merge this pr

**Comment by panwar8279** [comment]
Please Create new PRs for this because it contains conflict issue.

**Pull request closed without merging**
