### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mahekkg**
Updated the README.md file to include detailed installation instructions and contribution guidelines. Also, reorganized the sections for better readability and added additional examples to illustrate the usage of the software. These changes aim to provide users with a clearer understanding of how to set up the project and contribute effectively, while also showcasing the project's capabilities in a more user-friendly manner.

Screenshot (379)
Screenshot (380)
Screenshot (381)

### CODE REVIEW

**Comment by raj03kumar** [comment]
> Updated the README.md file to include detailed installation instructions, contribution guidelines, and a comprehensive list of features for the project. Also, reorganized the sections for better readability and added additional examples to illustrate the usage of the software. These changes aim to provide users with a clearer understanding of how to set up the project and contribute effectively, while also showcasing the project's capabilities in a more user-friendly manner.

Please attach screenshot of the new readme.

**Comment by mahekkg** [comment]
Please leave a review.

**Review by raj03kumar — APPROVED** [review]
Good work...

**Comment by mahekkg** [comment]
> Good work...
Thank you 
Looking forward to assist on more task

**Comment by raj03kumar** [comment]
> > Good work...
> > Thank you
> > Looking forward to assist on more task

Let us know ur interest so that we can proceed with u.

**Pull request merged**
