### PR TITLE
Improve margin and padding in card

### LINKED ISSUE #423: Update card UI
### Description

Hi @raj03kumar, I am a contributor in GSSOC'23, 
I want to work on Improving layout of card.
I will add some margins and padding between title, desc, and button
please assign me this task under label gssoc'23

### Screenshots

Screenshot 2023-06-08 115110

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Ayush9951**
close #423 
Hi @raj03kumar, I've Improved padding and margin of the card, please check

Screenshot 2023-06-08 142545

### CODE REVIEW

**Review by raj03kumar — CHANGES_REQUESTED** [review]
There is one issue with this PR. The game number get's hidden because of increased margin and padding. We can't merge this PR.

**Comment by raj03kumar** [comment]
> There is one issue with this PR. The game number get's hidden because of increased margin and padding. We can't merge this PR.

Make changes so that the position of the number remains fixed in the card. Rest everything is good.

**Comment by Ayush9951** [comment]
card doesn't have enough padding to add a game number, any suggestions

**Comment by raj03kumar** [comment]
> card doesn't have enough padding to add a game number, any suggestions

leave it

**Pull request closed without merging**
