### PR TITLE
Make Animation Responsive

### LINKED ISSUE #385: [FEATURE] - Make Animation Responsive
### Description

Hi @raj03kumar, I am a contributor in GSSOC'23.
I want to work on Improving the responsiveness of pac-man animation for different device widths.
please assign me this task under label gssoc'23

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Ayush9951**
close #385
Hi @raj03kumar, I've successfully added media queries and Improve Animation, please consider merging my pull request with the main branch.

### CODE REVIEW

**Review by raj03kumar — CHANGES_REQUESTED** [review]
Everything is fine @Ayush9951 . Can you just increase the height of the ghosts as they are looking short and the impact is that their mouth is overlapping with their bodies. Kindly increase the height vertically. That would solve the problem.

**Comment by Ayush9951** [comment]
Hi @raj03kumar, Please explain for what width the issue is showing and how much height you want me to Increase?

**Comment by raj03kumar** [comment]
@Ayush9951 Can you make the preloader of the website also responsive. If you can then let me know and you can start working on it. Make a new PR for that. Good for u...

**Comment by raj03kumar** [comment]
> Hi @raj03kumar, you want the loading animation to be responsive also ?

Yeah that yellow color preloading animation to be responsive.

**Comment by raj03kumar** [comment]
> > Hi @raj03kumar, you want the loading animation to be responsive also ?
> 
> Yeah that yellow color preloading animation to be responsive.

Bring it to centre of the page

**Pull request merged**
