### PR TITLE
Improve Navbar and Scroll Effect

### LINKED ISSUE #354: Improve Navbar and Scroll Effect
### Description

Hi, @panwar8279, I am a contributor in GSSOC'23.
I want to work on Improving the Navbar and scroll effect
Navbar doesn't have equal margin and padding. 
Scroll bar animation is not smooth.
please assign me this task under label gssoc'23.

### Screenshots

Screenshot 2023-06-05 124711

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Ayush9951**
close #354 
Hi, I've Improve the margin and padding in Navbar and add smooth scrolling animation.
Please consider merging the pull request in the main branch, and If any changes required please let me know.

### CODE REVIEW

**Review by raj03kumar — CHANGES_REQUESTED** [review]
This PR has some merge conflicts. Kindly resolve it and make a new PR so that we can merge your work. All the best.

**Comment by raj03kumar** [comment]
> Hi @raj03kumar, can you please explain in which file merge conflicts are showing ? so I can work on fixing the issue

Just go to your fork and it will come that your repo is behind the main branch or something and sync your branch and then create a pull request. I hope it will work.

**Comment by raj03kumar** [comment]
> ok @raj03kumar, I checked merge conflicts are in package-lock.json file. If I remove this file before I made a commit and send a pull request will It work ?

No. You should not remove. That won't work

**Comment by raj03kumar** [comment]
Go to your repo and sync your repo. And then send the pull request.

**Comment by raj03kumar** [comment]
> Someone may have made changes in package-lock.json and you haven't pulled those changes that's why merge conflict arised. Kindly pull those changes and then proceed.

for pulling the changes sync your fork.

**Comment by Ayush9951** [comment]
ok @raj03kumar I'll try with sync fork

**Pull request closed without merging**
