### PR TITLE
Trivia game addded

### LINKED ISSUE #5: Trivia
Make a fun filled 90s Trivia game with good UI

### PR DESCRIPTION
**Pull request by Tushar98644**
Fixes #5 

@Shreyaar12 pls verify...

### CODE REVIEW

**Comment by Tushar98644** [comment]
just to clarify , i raised this pr under Gssoc'23 @raj03kumar @Shreyaar12

**Comment by raj03kumar** [comment]
> just to clarify , i raised this pr under Gssoc'23 @raj03kumar @Shreyaar12

bro the card u made is not visible in the deployment.... Can u put the screenshot as well

**Comment by Tushar98644** [comment]
> > just to clarify , i raised this pr under Gssoc'23 @raj03kumar @Shreyaar12
> 
> bro the card u made is not visible in the deployment.... Can u put the screenshot as well

ya sure......
Screenshot 2023-05-21 at 11 42 21 AM

**Comment by raj03kumar** [comment]
> > > just to clarify , i raised this pr under Gssoc'23 @raj03kumar @Shreyaar12
> > 
> > 
> > bro the card u made is not visible in the deployment.... Can u put the screenshot as well
> 
> ya sure...... Screenshot 2023-05-21 at 11 42 21 AM

of the homepage as well

**Comment by Shreyaar12** [comment]
Please add the card details in data.js in data folder as well. 
Kindly refer contributing.md while contributing @Tushar98644

**Pull request merged**
