### PR TITLE
Re-Play Button added

### PR DESCRIPTION
**Pull request by ishita80**
I have added Re-Play Button to Ninety-nine Game.
Re-Play Button

### CODE REVIEW

**Review by raj03kumar — CHANGES_REQUESTED** [review]
Good Feature Ishita. Please delete package-lock.json as it is causing merge conflicts. And also add css to the replay button {cursor: pointer}.

**Comment by ishita80** [comment]
Thank you Sir. What kind of css do you expect? 
Some hover or whole button to be changed?

**Comment by raj03kumar** [comment]
> Thank you Sir. What kind of css do you expect? Some hover or whole button to be changed?

just change the mouse cursor on hover

**Comment by ishita80** [comment]
Sir I have deleted package-lock.json file but it is still showing conflicts.
What should I do now?

**Comment by raj03kumar** [comment]
> Sir I have deleted package-lock.json file but it is still showing conflicts. What should I do now?

Make a new pull request

**Pull request closed without merging**
