### PR TITLE
Improve loading animation

### LINKED ISSUE #408: [FEATURE] Responsive Preloading Animation
### Description

Hi @raj03kumar, I am a contributor in GSSOC'23.
The preloading animation is not responsive, I would like to work on fixing this issue.
Please assign me this task under label gssoc'23

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Ayush9951**
close #408
Hi @raj03kumar, I've Improved the loading animation and make It responsive, Please check

### CODE REVIEW

**Review by raj03kumar — APPROVED** [review]
Good work...

**Comment by Ayush9951** [comment]
What can we Improve next ? Any suggestions

**Comment by raj03kumar** [comment]
> What can we Improve next ? Any suggestions

Can you loop the pacman animation.

**Comment by Ayush9951** [comment]
I can try but that issue is already assigned to someone else

**Comment by raj03kumar** [comment]
> I can try but that issue is already assigned to someone else

U can give it a shot. i will merge ur PR

**Pull request merged**
