### PR TITLE
[Gssoc '23] Adding Connect 4 Game

### PR DESCRIPTION
**Pull request by varunshankar07**
Connect Four is a competitive game where players strategize and try to out manoeuvre their opponent by strategically placing their coloured discs in a grid. The game requires critical thinking and planning ahead to block the opponent's moves while setting up opportunities for their own victories. The player who successfully connects four discs of their colour first wins the game. ☺️💿

Features : 🚚🤺

1. Disc Colours: Players choose their preferred colour, often represented by red and yellow discs.
2. Turn-Based Gameplay: Players take turns dropping one disc at a time into the grid.
3. Win Conditions: The game detects and declares a winner if a player successfully connects four of their discs in a row, 
 horizontally, vertically, or diagonally.
4. Simple User Interface: The game features an intuitive and user-friendly interface for easy interaction.

Tech Stacks : [Html, Css And Javascript]

### CODE REVIEW

**Comment by varunshankar07** [comment]
> Connect Four is a competitive game where players strategize and try to out manoeuvre their opponent by strategically placing their coloured discs in a grid. The game requires critical thinking and planning ahead to block the opponent's moves while setting up opportunities for their own victories. The player who successfully connects four discs of their colour first wins the game. ☺️💿
> 
> Features : 🚚🤺
> 
> 1. Disc Colours: Players choose their preferred colour, often represented by red and yellow discs.
> 2. Turn-Based Gameplay: Players take turns dropping one disc at a time into the grid.
> 3. Win Conditions: The game detects and declares a winner if a player successfully connects four of their discs in a row,
>    horizontally, vertically, or diagonally.
> 4. Simple User Interface: The game features an intuitive and user-friendly interface for easy interaction.
> 
> Tech Stacks : [Html, Css And Javascript]
> 
>    

Fixes: #270

**Comment by varunshankar07** [comment]
@panwar8279 Could You Look Into This And Merge The Pr😊 >>And Point Out Issues If Any!

**Comment by varunshankar07** [comment]
@panwar8279 Could You Look Into This!!??

**Review by raj03kumar — CHANGES_REQUESTED** [review]
The checks didn't pass. Kindly resolve it.

**Pull request closed without merging**
